local/include/core/ProxyVerifier.h, local/src/core/ProxyVerifier.cc
Before this change, we assumed that the url YAML element had the scheme, authority, and path from which we populated the HTTP/2 pseudo header fields. However, the url element may just have the path. This updates the parser to also look for the scheme from the YAML element and, if the url doesn't have it, grabs the authority from the Host header field.
=> Updating the parsing of HTTP/2 pseudo header fields.

README.md, local/include/core/ProxyVerifier.h, local/src/core/ProxyVerifier.cc, test/autests/gold_tests/field_parsing/gold/duplicate_fields_client.gold, test/autests/gold_tests/field_parsing/gold/duplicate_fields_proxy.gold, test/autests/gold_tests/field_parsing/gold/duplicate_fields_server.gold, test/autests/gold_tests/field_verification/field_verification.test.py, test/autests/gold_tests/field_verification/http_replay_files/duplicate_fields/duplicate_field_verification.yaml, test/unit_tests/test_ProxyVerifier.cc
- Changes the _rules member variable to be a multimap so that it can support duplicate field verification. 
- Updates the Rules classes to support duplicate fields.
- Updates the YAML parser to support field value sequences as a way to express duplicate fields.
This address issue: https://github.com/yahoo/proxy-verifier/issues/5
=> Adding duplicate field validation support.

local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc, test/autests/gold_tests/field_parsing/gold/duplicate_fields_client.gold, test/autests/gold_tests/field_parsing/gold/empty_proxy_client.gold, test/autests/gold_tests/field_parsing/gold/empty_proxy_server.gold, test/autests/gold_tests/field_parsing/gold/yaml_specified_client.gold, test/autests/gold_tests/https/gold/single_transaction_server.gold
This addresses random EINVAL errors I was seeing on accept(). Also, adding a warning for transactions that take longer than 2 seconds to process. It took me a while to find that one response out of some 100,000 transactions without a content-length nor chunked encoded body took 30 seconds to time out. This will hopefully help track such issues down.
=> Initialize variables and warn on transactions that that longer than 2 seconds

local/src/core/ProxyVerifier.cc
=> Original could would not find the original root slash and so not set the :path psuedo header

local/include/core/ProxyVerifier.h, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc
- This adds logging of delayed HTTP/2 transactions.
- It also adds cleanup of the H2StreamState instances.
=> Adding HTTP/2 timestamp and fix a leak

Sconstruct, local/include/core/ArgParser.h, local/include/core/ProxyVerifier.h, local/src/client/verifier-client.cc, local/src/client/verifier-client.part, local/src/core/ArgParser.cc, local/src/core/ProxyVerifier.cc, local/src/core/core.part, local/src/server/verifier-server.cc, local/src/server/verifier-server.part, test/autests/gold_tests/field_parsing/gold/empty_proxy_client.gold, test/autests/gold_tests/field_parsing/gold/yaml_specified_client.gold, test/autests/gold_tests/https/gold/single_transaction_client.gold, test/autests/gold_tests/https/gold/single_transaction_proxy.gold, test/autests/gold_tests/https/replay_files/single_transaction/single_http_transaction.yaml, test/unit_tests/test_ProxyVerifier.cc, test/unit_tests/test_chunk_parsing.cc, test/unit_tests/unit_tests.part
This adds '-Wall', '-Wextra', '-Werror' compiler flags and fixes the
associated warnings.
It also fixes a few leaks detected by ASan.
It also adds unit tests to chunked-encoded parsing and makes some
adjustements accordingly. I don't believe, in the end, this changed much
behaviorally, but it could in theory make the client read the entire
final chunk (the zero-body one) when, before, it could have stopped
reading that after the entire expected body was received. But any
previous "bad" behavior would require specific read behavior such that
the final chunk was on a different read than the rest, which maybe is
unlikely. And even then, I'm not sure if something bad would have
happened.
The big behavioral change is having the server close the connection
after the entire writing of the body …
=> '-Wall', ASan leak fixes, connection close on unspecified bodies

.clang-format, local/include/core/ArgParser.h, local/include/core/ProxyVerifier.h, local/include/core/yaml_util.h, local/src/client/verifier-client.cc, local/src/core/ArgParser.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc, test/unit_tests/test_ProxyVerifier.cc, test/unit_tests/test_chunk_parsing.cc, test/unit_tests/unit_test_main.cc, tools/clang-format.sh
Adding a clang-format file. Without this, running clang format doesn't do much.
This is built off of the commit from this PR: https://github.com/yahoo/proxy-verifier/pull/19
As such, only review the clang-format PR.
This is a non-functional change. Only the format is changing with this PR.
=> Clang formatting with a clang-format file

local/include/core/ProxyVerifier.h, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc, test/autests/gold_tests/field_parsing/replay_files/duplicate_fields/duplicate_fields.yaml, test/autests/gold_tests/field_parsing/replay_files/empty_field/yaml_specified.yaml, test/autests/gold_tests/field_parsing/replay_files/empty_proxy/empty_proxy.yaml, test/autests/gold_tests/field_parsing/replay_files/transaction_fields/transaction_fields.yaml, test/autests/gold_tests/field_parsing/replay_files/yaml_specified/yaml_specified.yaml, test/autests/gold_tests/field_verification/http_replay_files/duplicate_fields/duplicate_field_verification.yaml, test/autests/gold_tests/field_verification/http_replay_files/json/transactions_with_verification.json, test/autests/gold_tests/field_verification/http_replay_files/yaml/cookie_equal.yaml, test/autests/gold_tests/format_argument/replay_files/unique_by_host/unique_by_host.yaml, test/autests/gold_tests/http/replay_files/multiple_transactions/file1.json, test/autests/gold_tests/http/replay_files/multiple_transactions/file2.json, test/autests/gold_tests/http/replay_files/single_transaction/single_http_transaction.json, test/autests/gold_tests/http2/replay_files/single_transaction/single_transaction.json, test/autests/gold_tests/https/mtls.test.py, test/autests/gold_tests/https/replay_files/mtls.yaml, test/autests/gold_tests/https/replay_files/single_transaction/single_http_transaction.yaml, test/autests/gold_tests/ipv6/replay_files/single_transaction/single_http_transaction.yaml, test/autests/gold_tests/keys_arg/replay_files/five_transactions/five_transactions.yaml, test/autests/gold_tests/no_proxy/http_replay_file/single_http_transaction.json, test/autests/gold_tests/strict_mode/replay_files/fields_differ/single_http_transaction.json, test/autests/gold_tests/strict_mode/replay_files/fields_match/single_http_transaction.json
"sessions": [
{
"protocol": [
{
"name": "http",
"version": "2"
},
{
"name": "tls",
"version": "TLSv1.2",
"sni": "www.tls.com",
"proxy-verify-mode": 0,
"proxy-provided-cert": true
},
{
"name": "tcp"
},
{
"name": "ip",
"version": "4"
}
],
...
"proxy-request": {
"protocol": [
{
"name": "http",
"version": "1.1"
},
{
"name": "tls",
"version": "TLSv1.2",
"sni": "www.tls.com",
"proxy-verify-mode": 1,
"proxy-provided-cert": false
},
{
"name": "tcp"
},
{
"name": "ip",
"version": "4"
}
],
=> Support the new protocol node format:

Sconstruct, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc
Updated libswoc to a dev 1.2.9 version which has a fix for
an implicit deprecated-copy constructor.
GCC 9 complains about returning with std::move for local variables
because it short circuits copy elision.
=> Fix Werror=deprecated-copy in libswoc, Werror=pessimizing-move

local/src/core/ProxyVerifier.cc
With enough TLS traffic, this would crash sometimes when a log message was attempted and ERR_reason_error_string was a nullptr.
=> Fixing a crash if ERR_reason_error_string returns a nullptr

test/autests/Pipfile, test/autests/gold_tests/http2/gold/single_transaction_client.gold_macos, test/autests/gold_tests/http2/gold/single_transaction_proxy.gold_macos, test/autests/gold_tests/http2/gold/single_transaction_server.gold_macos, test/autests/gold_tests/http2/http2.test.py, test/autests/gold_tests/https/gold/single_transaction_client.gold_macos, test/autests/gold_tests/https/gold/single_transaction_proxy.gold_macos, test/autests/gold_tests/https/gold/single_transaction_server.gold_macos, test/autests/gold_tests/https/https.test.py, test/autests/test-env-check.sh
The http2 test depends upon NPN support. This pins the cryptography
version to keep NPN support.
=> AuTest: pin the cryptography version to keep npn support

README.md, local/include/core/ProxyVerifier.h, local/src/core/ProxyVerifier.cc, test/autests/gold_tests/field_verification/http_replay_files/substr_rules/substr_rules.yaml, test/autests/gold_tests/field_verification/http_replay_files/substr_rules_duplicate/substr_rules_duplicate.yaml, test/autests/gold_tests/field_verification/substr_rules.test.py, test/unit_tests/test_ProxyVerifier.cc
Supports new rules for field verification. contains allows searching for substrings in any position of a field value, prefix at the beginning of a field value, and suffix at the end of a field value. For example:
```
- [ "Host", "stage.video.ex:", prefix ]
- [ "Path", ".jpg", suffix ]
- [ "Via", "traffic server", contains ]
```
=> Support contains, prefix, and suffix

local/src/core/ProxyVerifier.cc
The use of swoc::bwf::If crashes sometimes under load. Removing the call
of this for now.
=> Work around swoc::bwf::If crash.

test/autests/Pipfile, test/autests/gold_tests/autest-site/proxy_http2.py
The newest version of PyOpenssl breaks eventlet. I filed an opensource
bug with eventlet:
https://github.com/eventlet/eventlet/issues/671
Also, by simply removing the npn callback which we don't use anyway, we
no longer need to pin the cryptography version which is quite old at
this point.
=> Pin pyopenssl; memove npn cryptography dependency.

README.md, local/src/core/ProxyVerifier.cc, test/unit_tests/test_ProxyVerifier.cc
Fixes a bug with URL parsing when a scheme is missing (marker was not reset to 0 if missing)
=> Fix path/query parsing bug

local/src/core/ProxyVerifier.cc, test/autests/gold_tests/autest-site/proxy_http1.py, test/autests/gold_tests/body/body.yaml, test/autests/gold_tests/field_parsing/gold/transaction_fields_proxy.gold, test/autests/gold_tests/field_parsing/gold/transaction_fields_proxy.gold_macos, test/autests/gold_tests/field_parsing/gold/yaml_specified_proxy.gold, test/autests/gold_tests/field_parsing/gold/yaml_specified_proxy.gold_macos
We didn't send a zero-length chunked body for empty content chunked
encoded messages. This fixes that.
=> Fix handling of zero-length chunked bodies.

test/autests/Pipfile
The eventlet issue requiring us to pin PyOpenSSL has been resolved:
https://github.com/eventlet/eventlet/issues/671
Therefore we can remove the PyOpenSSL pin.
=> Removing the pyOpenSSL pin

local/include/core/ProxyVerifier.h, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc
Before this, the server had to get the key from a proxy-request node. If
an all:headers::fields::uid existed, it happened to get it from there,
but otherwise the server could not derive a key for a transaction
without a proxy-request. We don't want the user to be required to add
a proxy-request node, so this wasn't acceptable.
=> Update server to be able to derive key from just client-request

local/include/core/ProxyVerifier.h, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc
The transaction key is only required in the client-request, but logging
would sometimes show "*N/A*" if the server-response didn't have it. This
addresses that. I no longer see any "*N/A*" in any of the tests.
Fixes #86 
=> Make the response's key set in (hopefully) all instances.

local/src/client/verifier-client.cc, local/src/server/verifier-server.cc, test/autests/gold_tests/arguments/format_argument/format_argument.test.py, test/autests/gold_tests/arguments/format_argument/no_uuid.yaml, test/autests/gold_tests/autest-site/server.test.ext
This would have saved @SolidWallOfCode some hassle if Proxy Verifier more explicitly failed parsing when transactions without keys are found.
=> Fail parsing if transactions without keys are found.

local/include/core/ProxyVerifier.h, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc, test/autests/gold_tests/autest-site/proxy_http2.py, test/autests/gold_tests/http2/gold/http2_to_http2_proxy.gold, test/autests/gold_tests/http2/gold/http2_to_http2_server.gold
This address some issues shinrich found in prod testing. The biggest
changes are:
1. HTTP/2 now correctly sends body data if there is no Content-Length
header.
2. The mechanism by which HTTP/2 streams are handled is chanced such
that entire streams are handled at once rather than trying to separate
the read of headers vs body. The latter doesn't work if you get headers
for stream id 1, headers for stream id 3, then body for stream id 1, for
instance.
3. This also fixes poll_for_headers for HTTP/2 so that if requests are
read on a previous call, this will not block indefinitely.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of …
=> HTTP/2 stream handling fixes.

local/include/core/ProxyVerifier.h, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc
Fixing a memory leak found with ASan. The call to H2Session::init called
TLSSession::init with server_context after TLSSession::init already
called it for the same server_context. (Both TLSSession and H2Session
share the same server_context because they need not be different between
the two.) This caused server_context to be initialized twice with
SSL_CTX_new, with the first one being immediately overwritten by the
second, thus causing the first to be leaked.
=> Fixing memory leak of TLSSession::server_context 

local/include/core/Localizer.h, local/include/core/ProxyVerifier.h, local/include/core/YamlParser.h, local/include/core/case_insensitive_utils.h, local/src/client/verifier-client.cc, local/src/core/Localizer.cc, local/src/core/ProxyVerifier.cc, local/src/core/YamlParser.cc, local/src/core/core.part, local/src/server/verifier-server.cc
This separates YAML parsin and Localizer into YamlParser and Localizer,
each compiled into their own objects. This also adds YAML parsing timing
information.
=> Refactor: create YamlParser and Localizer classes.

local/src/client/verifier-client.cc, local/src/server/verifier-server.cc
Fix a crash that happened when:
1. User specified a non-existent file via --ca-certs.
2. Not specify a client or server cert.
Fixes #122 
=> Fix a command line processing crash for non-existent cert.

README.md, Sconstruct, local/src/client/verifier-client.part, local/src/core/core.part, local/src/server/verifier-server.part
Adding a scons --enable-asan option to build compile and link the
executables for ASan.
=> Adding --enable-asan option.

README.md, test/autests/test-env-check.sh
The latest brew upgrade resulted in the Python cryptography package
required for the AuTests to fail compilation. This detects if the user's
environment is macOS and sets the appropriate environment variables to
point installation to brew's openssl rather than the system SSL to
address this.
=> Fix cryptography autest pipenv package for macos

local/src/core/ProxyVerifier.cc
I noticed that I was still getting serialized sessions even when
"--thread-limit 1" was passed to the client. This was due to an
off-by-one bug in the ThreadPool::get_worker() logic.
---
=> Make "--thread-limt 1" serialize sessions.

local/src/client/verifier-client.cc, local/src/core/YamlParser.cc, local/src/server/verifier-server.cc
This avoids aborts from yaml-cpp code in certain circumstances by
testing that a node exists before retrieving data from it.
=> Verify YAML node existence before querying data on it.

README.md, local/include/core/YamlParser.h, local/src/client/verifier-client.cc, local/src/core/YamlParser.cc, local/src/server/verifier-server.cc, test/autests/gold_tests/delay/client-side-delay.yaml, test/autests/gold_tests/delay/delay.test.py, test/autests/gold_tests/delay/server-side-delay.yaml
This commit adds the ability to specify a server-side delay.
=> Adding server-side delay specification.

README.md, local/include/core/http.h, local/include/core/http2.h, local/src/client/verifier-client.cc, local/src/core/http.cc, local/src/core/http2.cc, local/src/server/verifier-server.cc
Supports an options that sends a bound-to device for all client sockets on verifier-client.
=> Interface support

Pipfile
The latest scons-parts (0.16.0) does not work with the our parts files
as is.
=> Pinning to scons-parts 0.15.8

README.md, Sconstruct
--with-libs allows the user to specify the four various libraries with a
single option, instead of each individually. They all must exist
directly under a single directory with the names 'openssl', 'nghttp2',
'ngtcp2', and 'nghttp3'.
=> Add the --with-libs convenience option.

Sconstruct, tools/build_library_dependencies.sh
This updates the OpenSSL and HTTP library dependencies as they have
changed. The nghttp2 commit that was previously referenced got removed
due to a rebase in that repository, so that needed to be updated. Also,
curl and ATS have moved to using quictls/openssl instead of
tatsuhiro-t/openssl for OpenSSL. This updates that as well.
=> Updating the HTTP library dependencies.

Pipfile
The latest 4.2.x breaks scons-parts.
=> Pin to scons 4.1.0

Sconstruct, local/src/core/http3.cc
nghttp2 quic branch rebases periodically. We then need to update the
commit we've pinned to.
=> Updating nghttp2 quic commit.

local/src/core/http2.cc
We had a sleep_for to space out HTTP/2 transactions (streams) within a
session to adhere to the --rate parameter. This caused delays, though,
for reading responses for other streams. The sleep_for is unnecessary:
the reading from the socket has a timeout that corresponds to our delay
anyway. Simply remove the sleep_for to fix the timing issue.
=> HTTP/2 timing fix for --rate

README.md, tools/build_static
Provides a tool to automatically link the binaries statically.
=> Adding tools/build_static

Sconstruct, lib/openssl.part, local/src/core/https.cc, tools/build_library_dependencies.sh
openssl-3.0.1-quic introduces a bad performance regression to
proxy-verifier. I'll hold off on the upgrade until later.
This reverts commits:
e5e7430333fec57befb33da9072cc5d6932bb25d
797d4fe3b24bf69281afc6d7ef7463a96dbcf0a8
b5bb466040319be039a624a51ab44fd68949dc69
=> Revert "Build with openssl-3.0.1-quic. (#182)"

tools/build_library_dependencies.sh
Otherwise later libraries (like ngtcp2) can't read earlier ones (like
openssl) when they are built.
=> chmod each install dir as it is installed.

Sconstruct
This fixes compiler warnings from later compilers, such as gcc 11.
=> Updated to libswoc 1.3.7

Sconstruct, local/src/core/http3.cc, tools/build_library_dependencies.sh
This updates the various build tools to openssl 1.1.1n
=> Update library builds to use openssl 1.1.1n

tools/build_library_dependencies.sh, tools/build_static
On a mac, better to use the number of hyperthreaded cores, not just
physical cores.
=> hw.physicalcpu -> hw.logicalcpu

test/autests/Pipfile, test/autests/autest.sh, test/autests/gold_tests/autest-site/init.cli.ext, test/autests/gold_tests/autest-site/proxy_http2.py, test/autests/gold_tests/doctest/gold/doctest_server.gold, test/autests/gold_tests/http/replay_files/multiple_transactions/file1.json, test/autests/gold_tests/http/replay_files/multiple_transactions/file2.json, test/autests/gold_tests/http2/gold/http2_to_http1_client.gold, test/autests/gold_tests/http2/gold/http2_to_http1_proxy.gold, test/autests/gold_tests/http2/gold/http2_to_http1_server.gold, test/autests/gold_tests/http2/gold/http2_to_http2_client.gold, test/autests/gold_tests/http2/gold/http2_to_http2_proxy.gold, test/autests/gold_tests/http2/gold/http2_to_http2_server.gold, test/autests/gold_tests/http2/http2.test.py, test/autests/gold_tests/http2/replay_files/http2_to_http1.yaml, test/autests/gold_tests/http2/replay_files/http2_to_http2.yaml, test/autests/gold_tests/http2/replay_files/set_alpn.yaml, test/autests/test-env-check.sh
hyper, heretofore our test proxy's HTTP/2 package, is no longer
supported and does not work with Python 3.10. We therefore need to
switch it out for a different HTTP/2 Python package. httpx is the
recommended replacement by the final commit in hyper and seems to work
OK.
Switch to httpx goes pretty well, but the server gold file expectations
need to be updated because httpx is "smarter" about accept-*,
user-agent, host headers, and the like.
=> Test Proxy: switching to httpx from hyper.

local/include/core/http.h, local/src/core/http.cc
Enforce at least an empty chunk response body for chunked responses.
This will catch issues from the proxy.
=> Make chunk processing more strict.

local/src/core/https.cc
Printing the ALPN string from the proxy can be helpful for ALPN
behavior confirmation.
=> Print the proxy's incoming ALPN string on the verifier server

tools/build_library_dependencies.sh
For users whose root mask is restricted, we chmod the output directies so they are group/other readable. This applies that chmod to the install dir itself.
=> build_library_dependencies.sh: chmod the install dir

README.md, local/include/core/YamlParser.h, local/include/core/http.h, local/include/core/http2.h, local/include/core/http3.h, local/src/core/YamlParser.cc, local/src/core/http2.cc, local/src/core/http3.cc, test/autests/gold_tests/autest-site/proxy_http2.py, test/autests/gold_tests/await/await.replay.yaml, test/autests/gold_tests/await/await.test.py
Add the ability to specify that a stream should not be sent until the responses for a set of streams are received.
=> Add the await directive for HTTP/2 streams.

local/src/core/ArgParser.cc
The ArgParser::invoke() function will raise an exception, resulting in a crash, if no top-level arguments are provided to verifier-client or verifier-server. Rather than crashing, this patch exits early with an error string and a help message if no commands or options are provided.
=> Fix top-level crash when no arguments provided

local/include/core/YamlParser.h, local/src/core/YamlParser.cc, test/autests/gold_tests/http/http.test.py, test/autests/gold_tests/http/replay_files/multiple_transactions/file3.yaml
This fixes the explicit setting of the HTTP/1.0 or HTTP/1.1 string in the replay file via the version string.
=> Fix HTTP/1.x explicit version replay.

Pipfile, local/include/core/YamlParser.h, local/include/core/http.h, local/include/core/http3.h, local/include/core/proxy_protocol_util.h, local/src/client/verifier-client.cc, local/src/core/core.part, local/src/core/http.cc, local/src/core/http3.cc, local/src/core/proxy_protocol_util.cc, local/src/server/verifier-server.cc, test/autests/gold_tests/autest-site/proxy_http1.py, test/autests/gold_tests/autest-site/proxy_http2.py, test/autests/gold_tests/autest-site/proxy_protocol_context.py, test/autests/gold_tests/proxy-protocol/gold/http_single_transaction_client.gold, test/autests/gold_tests/proxy-protocol/gold/http_single_transaction_proxy.gold, test/autests/gold_tests/proxy-protocol/gold/http_single_transaction_server.gold, test/autests/gold_tests/proxy-protocol/gold/https_single_transaction_client.gold, test/autests/gold_tests/proxy-protocol/gold/https_single_transaction_proxy.gold, test/autests/gold_tests/proxy-protocol/gold/https_single_transaction_server.gold, test/autests/gold_tests/proxy-protocol/gold/ipv6_client.gold, test/autests/gold_tests/proxy-protocol/gold/ipv6_server.gold, test/autests/gold_tests/proxy-protocol/proxy_protocol.test.py, test/autests/gold_tests/proxy-protocol/replay_files/http_single_transaction_no_pp.replay.yaml, test/autests/gold_tests/proxy-protocol/replay_files/http_single_transaction_pp_v1.replay.yaml, test/autests/gold_tests/proxy-protocol/replay_files/http_single_transaction_pp_v2.replay.yaml, test/autests/gold_tests/proxy-protocol/replay_files/https_single_transaction_pp_v1.replay.yaml, test/autests/gold_tests/proxy-protocol/replay_files/https_single_transaction_pp_v2.replay.yaml, test/autests/gold_tests/proxy-protocol/replay_files/single_transaction_ipv6_pp_v1.replay.yaml, test/autests/gold_tests/proxy-protocol/replay_files/single_transaction_ipv6_pp_v2.replay.yaml
Added PROXY protocol support in proxy verifier:
- The verifier can send a PROXY header to the target it's connecting to if specified in the replay file
- The server will detect the PROXY header at the beginning of the connection and displays it when it sees a valid header
Note that at this point, sending custom PROXY protocol content is not supported. The PROXY header the client sends would have the source address and port set to it's local address, and the destination address and port set to the target address it's connecting to, which similar to what the `--haproxy-protocol` does in `curl`.
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution …
=> Added PROXY protocol support

local/src/core/YamlParser.cc, local/src/core/http2.cc, test/autests/gold_tests/delay/client-side-delay.yaml, test/autests/gold_tests/delay/delay.test.py
This fixes the parsing of delay specification when HTTP/2 frames nodes are used.
=> Fix client-request delay when h2 frames specfied

README.md, local/include/core/YamlParser.h, local/include/core/http.h, local/include/core/http3.h, local/include/core/proxy_protocol_util.h, local/src/client/verifier-client.cc, local/src/core/http.cc, local/src/core/http3.cc, local/src/core/proxy_protocol_util.cc, test/autests/gold_tests/autest-site/proxy_protocol_context.py, test/autests/gold_tests/proxy-protocol/proxy_protocol.test.py, test/autests/gold_tests/proxy-protocol/replay_files/http_pp_v1_with_address.replay.yaml
This PR contains the following changes:
* Allow specifying the source and destination address(the PROXY header content) in the replay file
* Updated the test proxy to send PROXY header with the source and destination address matching the PROXY header it received from the client
* Updated the README.md for PROXY protocol support
Note: if user doesn't specify source and destination addresses in the replay file, it will retain the `curl --haproxy-protocol` behavior, aka using the endpoint address of the underlying socket as the source and destination addresses.
=> add address specification for PROXY protocol

README.md, local/src/core/http.cc, test/autests/gold_tests/status_verification/replay_files/status_verification.yaml, test/autests/gold_tests/status_verification/status_verification.test.py
This PR adds the HTTP response reason string verification, as proposed in #227 .
=> Added HTTP response reason string verification

README.md, local/include/core/http.h, local/include/core/http2.h, local/src/core/YamlParser.cc, local/src/core/http2.cc, test/autests/gold_tests/autest-site/proxy_http2.py, test/autests/gold_tests/http2_abort/http2_abort.test.py, test/autests/gold_tests/http2_frames/gold/client.gold, test/autests/gold_tests/http2_frames/gold/server.gold, test/autests/gold_tests/http2_frames/http2_frames.test.py, test/autests/gold_tests/http2_frames/http2_frames.yaml, test/autests/gold_tests/http2_frames/verify_duration.py
Add the interface for adding delay before sending H2 frames, and add support to send h2 request and response frame by frame.
=> Add the interface for adding delay before sending H2 frames

local/src/core/YamlParser.cc, local/src/core/http2.cc
The pseudo-header validation logic is updated to enforce the following specified by the RFC:
should at least include the `:method` , `:scheme` and `:path` pseudo-header fields. `:authority` is not strictly requried.
* must omit the `:scheme` and `:path` pseudo-header fields.
* must include the `:authority` pseudo-header field.
should include and only include the `:status` pseudo-header field.
This resolves #252.
=> Updated HTTP/2 pseudo-headers enforcement logic

tools/build_library_dependencies.sh
Modify build_library_dependencies.sh to cleanup the build directory on success.
=> library build: cleanup the build directory on succcess

tools/build_library_dependencies.sh
Fix the checkout of nghttp2 in build_library_dependencies.
=> nghttp2 v.1.54.0 -> v1.54.0

test/autests/gold_tests/autest-site/server.test.ext
Being specific to v4 and v6 has performance benefits and is more correct. It also works around a limitation in autest where generic PortOpen doesn't work if localhost doesn't include v6.
=> server.test.ext: Use PortOpenv[46] When Condition

test/autests/Pipfile, test/autests/gold_tests/autest-site/proxy_http2.py, test/autests/gold_tests/autest-site/proxy_protocol_context.py, test/autests/gold_tests/doctest/gold/doctest_server.gold, test/autests/gold_tests/http2/gold/http2_to_http2_server.gold, test/autests/gold_tests/http2/http2.test.py, test/autests/gold_tests/http2/replay_files/http2_to_http2.yaml, test/autests/gold_tests/http2/replay_files/set_alpn.yaml, test/autests/gold_tests/http2_abort/http2_abort.test.py
Currently the http2 test proxy uses the httpx library, which works great in general. However it doesn't support trailer header. As we are working on adding trailer header support in Proxy Verifier,  it would be good to have the test proxy support trailer header, so that we can verify the proper functionality of the feature.
This PR updates the http2 test proxy, replacing the usage of  `httpx` with the `python-hyper/h2` library.  The `h2` is a lower-level library that supports trailer header and is used in the client-facing logic already. Verified that after these changes(with adjusted expectations), all existing tests pass.
Note that while this PR updates the test proxy to use a library that can support trailer header, the actual trailer header handling logic in the proxy would be added …
=> Update http2 test proxy to use the h2 lib

local/include/core/http3.h, local/src/core/http3.cc
Pull in ngtcp2 curl expiry logic from curl master and the currently unmerged https://github.com/curl/curl/pull/11390.
=> Updates concerning ngtcp2 expiry from curl.

local/include/core/YamlParser.h, local/include/core/http.h, local/src/core/YamlParser.cc, local/src/core/http.cc, local/src/core/http2.cc, local/src/core/http3.cc
Mostly, this updates HTTP/1 Expect: 100-continue handling to not send the body until a 100 Continue response is received.
=> Update Expect: 100-continue header support.

local/src/core/http3.cc
This fixes an infinite loop while waiting for incoming responses when a connection has been closed.
=> H3Session::receive_responses: detect closed connection

local/src/core/http2.cc
pack_headers would always malloc trailers even if there were none. This caused issues with some HTTP/2 traffic that didn't have trailers. This patch short-circuits the pack in these cases.
=> If there are no trailer headers, do not pack them

local/src/core/YamlParser.cc
We should stop processing a transaction list if the element is not a sequence. This will propagate an error rather than aborting with an uncaught exception later.
Fixes #289
=> Gracefully handle non-sequence transactions

test/autests/Pipfile
The latest release, 1.2.0, causes the http3 tests to fail. For now, pinning to 1.1.0 from last week.
=> pin aioquic to 1.1.0

Sconstruct, tools/build_library_dependencies.sh
wladd's openssl 3.3 quictls patch has not landed yet. This transitions us to using that branch in the meantime until it lands.
=> Use openssl quic wladd/quic-on-3.3-dirty

local/include/core/ArgParser.h, local/parts/proxy-verifier.part
=> Prepare for v2.12.1

local/include/core/ProxyVerifier.h, local/include/core/YamlParser.h, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/core/YamlParser.cc, local/src/server/verifier-server.cc
Separates reader and parser threads, in case that's helpful someday. It looks like the majority of the time is taken up in YAML parsing, shifting memory.
=> Support Ctrl-C for parsing YAML

local/include/core/SocketNotifier.h, local/include/core/SocketPoller.h, local/include/core/http.h, local/include/core/http2.h, local/include/core/http3.h, local/include/core/https.h, local/src/client/verifier-client.cc, local/src/core/SessionFactory.cc, local/src/core/SocketNotifier.cc, local/src/core/SocketPoller.cc, local/src/core/core.part, local/src/core/http.cc, local/src/server/verifier-server.cc
Rather than have each of the thousands of session polling threads calling their own invocations of poll(2), this consolidates it to a single poll(2) system call for each of the file descriptors. Maybe this will make things more efficient.
=> Consolidate polling to a single poll'ing thread

local/src/core/SocketPoller.cc
perf mem highlighted _stop_polling as being a hot spot of memory allocations and frees. This should alleviate that.
=> Better memory management in _start_polling.

local/include/core/ProxyVerifier.h, local/src/client/verifier-client.cc, local/src/core/ProxyVerifier.cc, local/src/server/verifier-server.cc
Not functional, mostly renames. Although locks are unlocked before notify, since that is supposed to be more performant.
 
=> worker thread updates.

local/include/core/http.h, local/src/core/http.cc
Ensure that indexing into STATUS_NO_CONTENT does not overrun the buffer.
=> Address STATUS_NO_CONTENT overrun
