local/src/core/ProxyVerifier.cc
test/autests/gold_tests/field_parsing/empty_proxy.test.py
test/autests/gold_tests/field_parsing/gold/empty_proxy_client.gold
test/autests/gold_tests/field_parsing/gold/empty_proxy_proxy.gold
test/autests/gold_tests/field_parsing/gold/empty_proxy_server.gold
test/autests/gold_tests/field_parsing/replay_files/empty_proxy/empty_proxy.yaml

This addresses https://github.com/yahoo/proxy-verifier/issues/3

Allow empty proxy-request and proxy-response nodes.

---

local/src/client/verifier-client.cc

--sleep-limit unit fix: ms -> microseconds

---

local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc

Fix _key_format - it can be corrupted if set from the command line.

---

.gitignore
CMakeLists.txt
Sconstruct
lib/libyaml-cpp.part
lib/libyaml-cpp.pc.in
local/src/client/verifier-client.part
local/src/core/core.part
local/src/server/verifier-server.part

CMake building support changes.

---

test/autests/gold_tests/http2/gold/single_transaction_proxy.gold
test/autests/gold_tests/http2/gold/single_transaction_server.gold

Susan fixed path parsing. A gold file needs to be updated for this fix.

Updating the http2 gold file for the fixed path

---

local/src/core/ProxyVerifier.cc
test/unit_tests/test_ProxyVerifier.cc
test/unit_tests/unit_tests.part

HttpHeader::parse_url fixes and unit test

---

local/src/client/verifier-client.cc
test/autests/gold_tests/format_argument/format_argument.test.py
test/autests/gold_tests/format_argument/replay_files/unique_by_host/unique_by_host.yaml

This does some testing of the use of --format to make sure it functions as expected. Let me know if there's something else you'd like to test.

Adding --format to the client and adding --format AuTest

---

local/src/core/ProxyVerifier.cc
test/autests/gold_tests/field_parsing/gold/empty_proxy_client.gold
test/autests/gold_tests/field_parsing/gold/yaml_specified_client.gold

Add some errata notes and initialize num_drained_bytes with initial.size()

---

README.md
local/src/client/verifier-client.cc
local/src/core/ProxyVerifier.cc

Adding README descriptions of most optional arguments.

---

local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc

Stop processing transactions on reconnect failure

---

CONTRIBUTING.md
tools/clang-format.sh

clang_format.sh: make local and test dirs default.

---

tools/replay_gen.py

Ran into these issues when creating replay script for testing QAT engine.

Don't add content for GET and fix host header for replay_gen

---

README.md
local/src/client/verifier-client.cc
local/src/core/ProxyVerifier.cc
test/autests/gold_tests/arguments/format_argument/format_argument.test.py

The rendered README can be seen here:
https://github.com/bneradt/proxy-verifier/tree/rate_repeat_docs
---

Adding --rate, --repeat, and --format docs.

---

local/include/core/ProxyVerifier.h
local/src/client/verifier-client.cc
local/src/core/ProxyVerifier.cc
local/src/server/verifier-server.cc
test/autests/gold_tests/arguments/format_argument/format_argument.test.py
test/autests/gold_tests/arguments/repeat_argument/repeat_argument.test.py
test/autests/gold_tests/autest-site/proxy_http1.py
test/autests/gold_tests/autest-site/server.test.ext
test/autests/gold_tests/field_parsing/duplicate_fields.test.py
test/autests/gold_tests/field_parsing/gold/yaml_specified_server.gold
test/autests/gold_tests/field_parsing/gold/yaml_specified_server.gold_macos
test/autests/gold_tests/field_parsing/parse_yaml.test.py
test/autests/gold_tests/field_parsing/replay_files/empty_proxy/empty_proxy.yaml
test/autests/gold_tests/field_parsing/replay_files/yaml_specified/yaml_specified.yaml
test/autests/gold_tests/field_verification/field_verification.test.py
test/autests/gold_tests/http/gold/single_transaction_client.gold
test/autests/gold_tests/http/gold/single_transaction_client.gold_macos
test/autests/gold_tests/http/replay_files/multiple_transactions/file2.json
test/autests/gold_tests/https/gold/single_transaction_server.gold
test/autests/gold_tests/strict_mode/strict_mode.test.py

* Only error on setrlimit with many parsed transactions.
* Add SIGINT handling to the server.
* Return code correctness improvements.
* Make proxy-* node optional.

Correctness testing improvements.

---

local/parts/proxy-verifier.part
local/src/client/verifier-client.part
local/src/core/core.part
local/src/server/verifier-server.part

Add pthread and version in build files

---

Sconstruct
local/parts/proxy-verifier.part

Also updating yaml-cpp.git reference to 0.6.3

Updating proxy-verifier.part for version 1.11.0.

---

README.md
local/src/core/ProxyVerifier.cc
local/src/server/verifier-server.cc

Logging and doc tweaks.

---

local/parts/proxy-verifier.part

Update part version to 1.11.2

---

local/include/core/ProxyVerifier.h
local/src/client/verifier-client.cc

Support --rate when no timing data is provided.

---

local/parts/proxy-verifier.part

Committing 1.11.4 PartVersion update.

---

local/include/core/ProxyVerifier.h
local/src/client/verifier-client.cc
local/src/core/ProxyVerifier.cc

This addresses issues where HTTP/2 transactions were being sent out in
parallel too quickly by applying rate limiting to them.

Apply rate limiting to transactions as well as sessions.

---

README.md
local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc
test/autests/gold_tests/autest-site/directive_engine.py
test/autests/gold_tests/autest-site/proxy_http1.py
test/autests/gold_tests/field_parsing/gold/yaml_specified_client.gold
test/autests/gold_tests/field_parsing/gold/yaml_specified_client.gold_macos
test/autests/gold_tests/field_parsing/gold/yaml_specified_server.gold
test/autests/gold_tests/field_parsing/gold/yaml_specified_server.gold_macos
test/autests/gold_tests/field_verification/field_verification.test.py
test/autests/gold_tests/field_verification/substr_rules.test.py
test/autests/gold_tests/strict_mode/strict_mode.test.py
test/autests/gold_tests/url_verification/replay_files/url_verification/url_verification.yaml
test/autests/gold_tests/url_verification/url_verification.test.py
test/unit_tests/test_ProxyVerifier.cc

Adds support for URL verification and refactors.

Start URL verification

---

local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc

Run clang-format.

---

Sconstruct

Updating to use libswoc v1.2.13.

---

local/parts/proxy-verifier.part

Setting the PartVersion to 1.12.1

---

local/src/client/verifier-client.cc
test/autests/gold_tests/arguments/keys_argument/keys_arg.test.py

Fixes a crash if --keys results in no transactions.

---

local/parts/proxy-verifier.part

Update part version to 1.12.2

---

local/src/server/verifier-server.cc

This fixes a bug in which non-block was accidentally set on the
listening socket instead of the accepted socket. This fixes some
situations where the server would hang if it did a read on one of these
blocking connections.

Set non-block on accepted sockets.

---

local/src/core/ProxyVerifier.cc

In a refactor, I missed calling sleep_for on the calculated delay_time
for HTTP/2 transactions. Adding that in.

Adds sleep_for accidentally missed for h2 transaction rate

---

Sconstruct
local/src/client/verifier-client.cc
local/src/core/ProxyVerifier.cc
local/src/server/verifier-server.cc

Use Rv::info/note/error, etc.

---

local/parts/proxy-verifier.part

Prepare for v1.12.3 release.

---

Sconstruct

Using libswoc version 1.2.17

---

test/autests/gold_tests/arguments/format_argument/format_argument.test.py
test/autests/gold_tests/arguments/keys_argument/keys_arg.test.py
test/autests/gold_tests/arguments/repeat_argument/repeat_argument.test.py
test/autests/gold_tests/autest-site/client.test.ext
test/autests/gold_tests/autest-site/ports.py
test/autests/gold_tests/autest-site/server.test.ext
test/autests/gold_tests/body/body.test.py
test/autests/gold_tests/field_parsing/duplicate_fields.test.py
test/autests/gold_tests/field_parsing/empty_field.test.py
test/autests/gold_tests/field_parsing/empty_proxy.test.py
test/autests/gold_tests/field_parsing/parse_yaml.test.py
test/autests/gold_tests/field_verification/field_verification.test.py
test/autests/gold_tests/field_verification/substr_rules.test.py
test/autests/gold_tests/http/gold/single_transaction_server.gold
test/autests/gold_tests/http/gold/single_transaction_server.gold_macos
test/autests/gold_tests/http/http.test.py
test/autests/gold_tests/http2/http2.test.py
test/autests/gold_tests/https/gold/single_transaction_server.gold
test/autests/gold_tests/https/https.test.py
test/autests/gold_tests/https/mtls.test.py
test/autests/gold_tests/ipv6/gold/single_transaction_server.gold
test/autests/gold_tests/ipv6/gold/single_transaction_server.gold_macos
test/autests/gold_tests/ipv6/ipv6.test.py
test/autests/gold_tests/no_proxy/no_proxy.test.py
test/autests/gold_tests/replay_gen/replay_gen.test.py
test/autests/gold_tests/strict_mode/strict_mode.test.py
test/autests/gold_tests/url_verification/url_verification.test.py

ports.py:get_port dynamically choosing an available port

---

test/autests/gold_tests/autest-site/ports.py

Change get_port to just use bind which is way quicker on mac

---

local/parts/proxy-verifier.part

Set part release to 1.13.0

---

local/src/server/verifier-server.cc

For TLS to function correctly, the Verifier server needs to be able to
understand the protocol:tls characteristics (like SNI). This previously
relied upon an explicit proxy-request:protocol:tls node, but it should
be able to assume the sessionsprotocol node as a default.

Make proxy-request protocol node option for tls.

---

README.md

Remove comma in URL parts list

---

README.md
local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc
local/src/server/verifier-server.cc
test/autests/gold_tests/arguments/format_argument/format_argument.test.py
test/autests/gold_tests/arguments/format_argument/uuid1.yaml
test/autests/gold_tests/arguments/format_argument/uuid2.yaml

Return a 404 for key not found.

---

local/include/core/ArgParser.h
local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc

intel compiler warnings patch

---

local/parts/proxy-verifier.part

update the part number to v1.14.1

---

README.md
test/autests/gold_tests/arguments/format_argument/unique_by_host.yaml
test/autests/gold_tests/body/body.yaml
test/autests/gold_tests/doctest/example_replay.yaml
test/autests/gold_tests/http/replay_files/single_transaction.yaml
test/autests/gold_tests/http2/replay_files/http2_to_http1.yaml
test/autests/gold_tests/http2/replay_files/http2_to_http2.yaml
test/autests/gold_tests/http2/replay_files/http2_to_http2_verification_failures.yaml
test/autests/gold_tests/http2/replay_files/set_alpn.yaml
test/autests/gold_tests/https/replay_files/mtls.yaml
test/autests/gold_tests/https/replay_files/single_transaction.yaml
test/autests/gold_tests/ipv6/replay_files/single_transaction.yaml
test/autests/gold_tests/no_proxy/replay/h2.yaml
test/autests/gold_tests/url_verification/url_verification.yaml

This also includes test tweaks concerning the protocol node.

Document the protocol node.

---

local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc

Fix an HTTP/2 use after free for composed url.

---

local/src/core/ProxyVerifier.cc

Run clang-format.sh

---

README.md
test/autests/gold_tests/doctest/example_replay.yaml
test/autests/gold_tests/doctest/gold/doctest_client.gold
test/autests/gold_tests/doctest/gold/doctest_server.gold

README update: Add use cases and other tweaks.

---

README.md
test/autests/gold_tests/doctest/example_replay.yaml

README tweak: add close quote.

---

README.md
test/autests/gold_tests/doctest/example_replay.yaml

Add a period in README comment.

---

local/src/core/ProxyVerifier.cc
test/autests/gold_tests/arguments/format_argument/format_argument.test.py
test/autests/gold_tests/arguments/format_argument/unique_by_url.yaml

Using URL as a key was broken. This adds a test for it and fixes it.

Fix --format {url}

---

local/parts/proxy-verifier.part

Preparing part version file for 1.14.2 release

---

local/include/core/ArgParser.h
local/src/core/ArgParser.cc
test/autests/gold_tests/arguments/version_argument/version_argument.test.py

Adds a verbose_argument.test.py to verify that the output is as
expected.

Update the output of --version

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing version data for the v1.14.3 release.

---

tools/update_version.sh

Add convenience script to update the version.

---

Sconstruct

This includes Intel compiler fixes.

Updating to libswoc 1.2.19

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for the v1.14.4 release

---

local/include/core/ProxyVerifier.h
local/include/core/YamlParser.h
local/src/core/ProxyVerifier.cc
local/src/core/YamlParser.cc

Running clang-format

---

README.md
local/include/core/ProxyVerifier.h
local/include/core/YamlParser.h
local/src/client/verifier-client.cc
local/src/core/ProxyVerifier.cc
local/src/core/YamlParser.cc
test/autests/gold_tests/delay/delay.test.py
test/autests/gold_tests/delay/delay.yaml
test/autests/gold_tests/delay/verify_duration.py
test/unit_tests/test_YamlParser.cc
test/unit_tests/unit_tests.part

Adds delay-ms node for sessions and transactions.

Add transaction and session delay specification ability.

---

local/src/core/CMakeLists.txt

Update CMakeLists for new cc files.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Updating to the v2.0.0 version.

---

tools/update_version.sh

Getting sed -i to work on both Linux and Mac is challenging.

Fixing update_version for mac and Linux.

---

README.md
local/src/core/YamlParser.cc
test/autests/gold_tests/body/body.yaml
test/autests/gold_tests/body/gold/body_client.gold
test/autests/gold_tests/body/gold/body_proxy.gold
test/autests/gold_tests/body/gold/body_server.gold
test/autests/gold_tests/http2/gold/http2_to_http2_client.gold
test/autests/gold_tests/http2/gold/http2_to_http2_proxy.gold
test/autests/gold_tests/http2/gold/http2_to_http2_server.gold
test/autests/gold_tests/http2/replay_files/http2_to_http2.yaml

This adds tests for specified bodies as well as updates the README
describing how to use them.

Fix specified chunk encoded bodies.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Versioning change for 2.0.1

---

README.md

Adding MacOS build instructions.

---

test/autests/Pipfile

Remove unneeded packages from autest Pipenv

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.0.2 release.

---

README.md

Add --thread-limit README description.

---

README.md

Do not make 1 emphatic in --thread-limit

---

README.md

Adding Ubuntu build commands.

---

README.md

Adding CentOS build notes.

---

README.md

Divide CentOS 8 and 7 into their own sections

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.1.0 release.

---

Sconstruct
local/src/client/verifier-client.part
local/src/core/core.part
local/src/server/verifier-server.part

Passing the parameter via mode supports building with this in more
contexts.

Make --enable-asn to use Parts mode parameter.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing version files for the v2.1.1 release

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for the v2.2.0 release.

---

docker/ubuntu/Dockerfile

Fixing the Ubuntu Dockerfile.

---

.gitignore
README.md
Sconstruct
lib/libev.part
lib/libevent.part
lib/libyaml-cpp.part
lib/nghttp2.part
lib/nghttp3.part
lib/ngtcp2.part
lib/openssl.part
local/src/client/verifier-client.part
local/src/core/core.part
local/src/server/verifier-server.part
test/autests/gold_tests/http3/gold/http3_to_http1_server.gold
test/unit_tests/unit_tests.part
tools/autopep8.sh
tools/build_library_dependencies.sh

Build OpenSSL, etc. from parts files.

---

docker/ubuntu/Dockerfile

Adding curl to Dockerfile.

---

docker/centos8/Dockerfile

Adding a centos8 Dockerfile.

---

README.md
docker/centos7/Dockerfile

Add a centos:7 Dockerfile.

---

tools/build_library_dependencies.sh

Update to use the quictls/openssl.git per curl's lead

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for the v2.2.1 release.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for the v2.2.2 release

---

tools/build_library_dependencies.sh

build_library_dependencies: update for new versions

---

local/src/core/http3.cc

clang-format update

---

Pipfile
Sconstruct
local/src/client/verifier-client.part
local/src/core/core.part
local/src/server/verifier-server.part

Use the latest scons and scons-parts.
Update to libswoc 1.2.23
Update the parts format to the new scons-parts 0.16.* format.

Update to the new scons and scons-parts

---

Pipfile
Sconstruct
local/include/core/http3.h
local/src/client/verifier-client.part
local/src/core/core.part
local/src/core/http3.cc
local/src/server/verifier-server.part
tools/build_library_dependencies.sh

Building with the latest h3 tools.

---

.pylintrc
test/autests/gold_tests/arguments/keys_argument/keys_arg.test.py
test/autests/gold_tests/arguments/port_argument/no_port_argument.test.py
test/autests/gold_tests/arguments/version_argument/version_argument.test.py
test/autests/gold_tests/autest-site/client.test.ext
test/autests/gold_tests/autest-site/directive_engine.py
test/autests/gold_tests/autest-site/ports.py
test/autests/gold_tests/autest-site/proxy.test.ext
test/autests/gold_tests/autest-site/proxy_http1.py
test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/autest-site/proxy_http3.py
test/autests/gold_tests/autest-site/replay_gen.test.ext
test/autests/gold_tests/autest-site/server.test.ext
test/autests/gold_tests/autest-site/socket_util.py
test/autests/gold_tests/delay/delay.test.py

Cleans up some common pylint issues and adds a start to the pylintrc
file. If we want to add this to our format script, some more work will
need to be added to the pylintrc file and (probably) to the Python
source files themselves.

Fixing some pylint issues

---

local/src/client/verifier-client.cc
local/src/core/http.cc
local/src/core/http2.cc

Nghttp2 poll crash fix

---

test/autests/gold_tests/autest-site/proxy_http1.py

proxy_http1.py format update

---

.gitignore

gitignore for some vim plugin artifacts

---

local/src/core/http2.cc
test/autests/gold_tests/autest-site/proxy_http1.py

Some copyright updates.

---

local/src/client/verifier-client.cc
local/src/core/http.cc

A couple more 2022 copyright updates.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for release v2.2.3

---

Sconstruct
lib/openssl.part
local/src/core/https.cc
tools/build_library_dependencies.sh

Build with openssl-3.0.1-quic.

---

Sconstruct
lib/openssl.part
tools/build_library_dependencies.sh

Have openssl-3 install to /lib instead of /lib64

---

Sconstruct
lib/openssl.part

openssl version typo fixes.

---

local/src/core/http.cc
local/src/core/http2.cc
local/src/core/https.cc

Some tweaks to handling session timeouts.

---

local/include/core/ProxyVerifier.h
local/src/core/ProxyVerifier.cc
local/src/core/YamlParser.cc
local/src/core/http3.cc
local/src/core/https.cc
local/src/core/verification.cc
local/src/server/verifier-server.cc
test/autests/gold_tests/arguments/format_argument/format_argument.test.py
test/autests/gold_tests/arguments/keys_argument/keys_arg.test.py
test/autests/gold_tests/http2/http2.test.py
test/autests/gold_tests/no_proxy/no_proxy.test.py
tools/build_library_dependencies.sh

2022 copyright updates.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for release 2.3.0

---

README.md
tools/build_static

Don't assume --with-libs=/opt. Allow the user to pass that as an
argument, though.

Some tweaks to build_static

---

tools/build_static

Fixing the build_static if the user doesn't use --with-libs=/opt

Fixing the mac link command

---

tools/build_library_dependencies.sh

build_library_dependencies_with_nproc: use nproc

---

tools/build_library_dependencies.sh

In case the user's mask restricts access.

chmod -R ugo+rX

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for v2.3.1 release

---

Sconstruct

yaml-cpp-0.7.0

---

local/src/core/YamlParser.cc
local/src/core/http.cc

Allow 999 response codes.

---

local/include/core/ArgParser.h
local/include/core/http.h

These two files were modified this year but haven't had their copyrights
updated yet.

Updating Copyrights to 2022

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.3.2 release

---

local/src/server/verifier-server.cc

Removed unused using declarations in verifier-server

---

README.md
tools/replay_gen.py

Add introduction of replay_gen to readme, fix h2 related replay file generation, and general bug fix.

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for version 2.3.3

---

tools/build_static

Fix build_static for macos

---

README.md
local/include/core/YamlParser.h
local/include/core/http.h
local/include/core/http2.h
local/include/core/http3.h
local/include/core/verification.h
local/src/core/YamlParser.cc
local/src/core/http.cc
local/src/core/http2.cc
local/src/core/http3.cc
local/src/core/verification.cc
local/src/server/verifier-server.cc
test/autests/gold_tests/body_verification/body_verification.test.py
test/autests/gold_tests/body_verification/http.yaml
test/autests/gold_tests/body_verification/http2.yaml
test/autests/gold_tests/body_verification/http3.yaml
tools/replay_gen.py

Add body verification, and some bug fixes for `replay_gen`.

Add body verification

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for v2.4.0 release

---

local/src/core/https.cc

Apply clang-format

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.4.1 release

---

local/include/core/https.h

ALPN: http1.1 -> http/1.1

---

local/src/core/http2.cc

This adds logging of information from the SETTINGS and WINDOW_UPDATE frames.

Adding SETTINGS and WINDOW_UPDATE logging

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for the v2.4.2 release

---

local/src/core/http2.cc

Handle connection errors during delay gracefully

---

README.md
local/include/core/YamlParser.h
local/include/core/http.h
local/include/core/http2.h
local/src/core/YamlParser.cc
local/src/core/http2.cc
test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/http2_abort/gold/server_after_headers.gold
test/autests/gold_tests/http2_abort/http2_abort.test.py
test/autests/gold_tests/http2_abort/replay_files/client_after_data.yaml
test/autests/gold_tests/http2_abort/replay_files/client_after_headers.yaml
test/autests/gold_tests/http2_abort/replay_files/server_after_headers.yaml

Allow h2 transactions to abort using rst_stream frame

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.5.0 release

---

local/src/core/ArgParser.cc

Update copyright for a ArgParser.cc

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for v2.5.1 release

---

tools/version_update.sh

Add version_update.sh safety checks to ensure it got the old version correctly.

version_update.sh updates

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.5.2 release

---

README.md
Sconstruct
lib/nghttp2.part
local/include/core/http.h
local/include/core/http2.h
local/src/core/YamlParser.cc
local/src/core/http2.cc
test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/http2_abort/gold/server_after_headers.gold
test/autests/gold_tests/http2_abort/http2_abort.test.py
test/autests/gold_tests/http2_abort/replay_files/client_goaway_after_headers.yaml
test/autests/gold_tests/http2_abort/replay_files/client_rst_stream_after_data.yaml
test/autests/gold_tests/http2_abort/replay_files/client_rst_stream_after_headers.yaml
test/autests/gold_tests/http2_abort/replay_files/server_goaway_after_headers.yaml
test/autests/gold_tests/http2_abort/replay_files/server_rst_stream_after_headers.yaml

Add support for GOAWAY frame, also adjusted the RST_STREAM frame autests.

Add support for GOAWAY frame

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

v2.6.0 version update

---

tools/build_static

This also fixes macos builds with --with-libs

Fix build_static for new parts output

---

test/autests/gold_tests/http2/gold/http2_to_http2_proxy.gold

Update http2 proxy gold file for StreamEnded

---

local/src/core/http.cc
local/src/core/http3.cc
test/autests/gold_tests/autest-site/proxy_http1.py
test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/autest-site/proxy_protocol_context.py
test/autests/gold_tests/proxy-protocol/proxy_protocol.test.py

Running tools/format.sh

---

local/src/core/YamlParser.cc

Fix body content reading from data frame

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.7.0 release

---

local/src/core/https.cc

Removed unused write_count variable

---

local/src/core/https.cc

https copyright update

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.8.0 release

---

tools/build_library_dependencies.sh

Fix a bug in darwin num cores calculation

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for v2.8.1 release.

---

test/autests/Pipfile

This has fixes for Python 3.11

Update to the latest autest release

---

Sconstruct
local/src/core/ProxyVerifier.cc
local/src/core/proxy_protocol_util.cc

This, among other things, fixes some warnings for the latest compilers.

libswoc update to 1.5.1

---

Sconstruct
local/src/core/http3.cc
tools/build_library_dependencies.sh

ngtcp2 v0.16.0; nghttp3 v0.12.0

---

local/src/core/http3.cc
local/src/core/proxy_protocol_util.cc

Unbeknownst to me, my local clang-format was broken earlier.

Run clang-format

---

lib/nghttp2.part
lib/nghttp3.part
lib/ngtcp2.part
lib/openssl.part

Update the lib .part files

---

local/src/server/verifier-server.cc

Set the key for 100-continue generated responses

---

test/autests/gold_tests/autest-site/ports.py

Update get_port to filter out listening ports via psutil.

Use psutil to filter out listening ports

---

test/autests/gold_tests/autest-site/ports.py

Removing debug print statement I left in.

---

Sconstruct
lib/openssl.part
tools/build_library_dependencies.sh

Bump the openssl dependency version to openssl-3.1.0+quic. 

Update openssl version to openssl-3.1.0+quic.

---

test/autests/gold_tests/autest-site/ports.py

Somehow I got the autest ports.py PortOpen logic reversed in my head. My psutil change makes this less impactful, but we might as well get this to be more accurate.

autest: Fix the PortOpen logic

---

README.md
local/include/core/http.h
local/include/core/http2.h
local/src/client/verifier-client.cc
local/src/core/YamlParser.cc
local/src/core/http.cc
local/src/core/http2.cc
local/src/core/http3.cc
local/src/server/verifier-server.cc
test/autests/gold_tests/http2_abort/http2_abort.test.py
test/autests/gold_tests/http2_abort/replay_files/client_rst_stream_mixed_data.yaml
test/autests/gold_tests/http2_frames/gold/multi_data_frame_client.gold
test/autests/gold_tests/http2_frames/gold/multi_data_frame_proxy.gold
test/autests/gold_tests/http2_frames/gold/multi_data_frame_server.gold
test/autests/gold_tests/http2_frames/http2_multi_data_frames.test.py
test/autests/gold_tests/http2_frames/http2_multi_data_frames.yaml

Supports multiple data frames

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for v2.10.0 release

---

lib/libyaml-cpp.part
lib/libyaml-cpp.pc.in

libyaml 0.8.0

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for v2.10.1 release

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Preparing for v2.11.0

---

local/src/core/Localizer.cc

This is needed for certain compilers.

Localizer.cc: add algorithm include

---

README.md
local/include/core/YamlParser.h
local/include/core/http.h
local/include/core/http2.h
local/src/client/verifier-client.cc
local/src/core/http2.cc
test/autests/gold_tests/autest-site/proxy.test.ext
test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/autest-site/test_proxy.py
test/autests/gold_tests/http2_strict_goaway/http2_strict_goaway.test.py
test/autests/gold_tests/http2_strict_goaway/http2_strict_goaway.yaml

Client stops initiating new streams after receiving GOAWAY frame

---

README.md
local/include/core/http.h
local/src/client/verifier-client.cc
local/src/server/verifier-server.cc

Add the optional argument to specify a timeout on read and write operations.

--poll-timeout

---

test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/autest-site/test_proxy.py

Format updates

---

README.md
local/include/core/YamlParser.h
local/include/core/http.h
local/include/core/http2.h
local/src/client/verifier-client.cc
local/src/core/http2.cc
test/autests/gold_tests/autest-site/proxy.test.ext
test/autests/gold_tests/autest-site/proxy_http2.py
test/autests/gold_tests/autest-site/test_proxy.py
test/autests/gold_tests/http2_strict_goaway/http2_strict_goaway.test.py
test/autests/gold_tests/http2_strict_goaway/http2_strict_goaway.yaml

Renaming strict-goaway to close-on-goaway

strict-goaway -> close-on-goaway

---

local/include/core/ArgParser.h
local/parts/proxy-verifier.part

Prepare for the v2.12.0 release

---

local/src/client/verifier-client.cc
test/autests/gold_tests/http2_close_on_goaway/http2_close_on_goaway.test.py

apply format

---

local/include/core/http.h
local/include/core/http2.h
local/src/core/http.cc
local/src/core/http2.cc
test/autests/gold_tests/http2/gold/http2_to_http2_client.gold
test/autests/gold_tests/http2/gold/http2_to_http2_server.gold

HTTP/2 expect: 100-continue updates.

---

Sconstruct
lib/nghttp2.part
lib/nghttp3.part
lib/ngtcp2.part
local/src/core/http.cc
local/src/core/http2.cc
local/src/core/http3.cc
test/autests/gold_tests/proxy-protocol/proxy_protocol.test.py
tools/build_library_dependencies.sh
tools/build_static

Replace deprecated apis and update lib versions

---

README.md
test/autests/gold_tests/field_verification/field_verification.test.py
test/autests/gold_tests/field_verification/replay_files/multi_value.yaml

Add test and documentation for multi-value field verification

---

lib/openssl.part

Update the openssl part reference

---

README.md
local/include/core/verification.h
local/src/core/verification.cc
test/autests/gold_tests/field_verification/field_verification.test.py
test/autests/gold_tests/field_verification/replay_files/multi_value_equal.yaml
test/autests/gold_tests/field_verification/replay_files/multi_value_includes.yaml

Add new "includes" verification check for multi-value verification 

---

local/src/core/verification.cc

Run format on master

---

local/src/core/YamlParser.cc

Cleanup of debug logs and running format that got missed in the last commit.

format and debug cleanup

---

local/include/core/http.h
local/src/client/verifier-client.cc
local/src/core/http.cc
local/src/core/http3.cc
local/src/core/https.cc

Print throughput metrics.

---

Sconstruct
lib/openssl.part
tools/build_library_dependencies.sh

Now that it has landed, might as well use it.

openssl-3.3.0+quic

---

local/include/core/http.h
local/src/core/http.cc

Remove _revents mutex deadlock

---

local/src/core/https.cc

SSLError{ssl_error}

---

README.md
local/src/client/verifier-client.cc

--run-continuously
